services:
  - type: web
    name: multilang_site
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn multilang_site.wsgi:application"
    workingDirectory: /opt/render/project/src